### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [BanzaiMan/travis_production_test#10]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by rkh** [comment]
lol

**Comment by BanzaiMan** [comment]
Is public domain OK?

**Comment by karan** [comment]
Yes it is perfect too!

**Comment by Condebk717** [comment]
Nothing works here in china even when I gets it all correctly
